#!/usr/bin/env bash
# This script configures nginx web server so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

redirected_location="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\n\t}"
file=/etc/nginx/sites-available/default

sed -i "42i\ $redirected_location" "file"

service nginx reload
