#!/usr/bin/env bash
# This script displays The content of the current directory in a list format
# Where only the part of the name after the first dash is displayed

list="$(ls -1 ./)"

for item in ${list}
do
	cut -d "-" -f 2 <<< "${item}"
done
