#!/usr/bin/env bash

# Firewall installation
apt-get update
apt-get install ufw

# Block all incoming traffic
ufw default deny incoming

# Except the following TCP ports
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

# Enable the firewall
ufw enable

# Check status
ufw status
